### ISSUE TITLE
Feature: Add to the backstage app-config the key: baxckend.auth.externalAccess to allow to access from external system backstage

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/stacks#53]
### Have you searched for this feature request?

- [x] I searched but did not find similar requests

### Problem Statement

The existing backstage instance do not allow to be accessed from an external system (Example: curl => backstage to post or get data) as the following [key](https://backstage.io/docs/auth/service-to-service-auth/#static-tokens) is not implemented within the ConfigMap => app-config

```
  auth:
    # Used for enabling authentication, secret is shared by all backend plugins
    # See https://backstage.io/docs/auth/service-to-service-auth for
    # information on the format
    externalAccess:
      - type: static
        options:
          token: ${BACKSTAGE_AUTH_TOKEN}
          subject: curl-requests
```

### Possible Solution

Patch the ConfigMap - data - app-config to add such a key
