### ISSUE TITLE
Bump the version of the ESO helm chart from: 0.9 to 0.15

### ISSUE THREAD

**Issue by cmoulliard** [cnoe-io/stacks#63]
## TODO

Bump the version of the ESO helm chart from to 0.15.1

```
// https://external-secrets.io/index.yaml
  external-secrets:
  - apiVersion: v2
    appVersion: v0.15.1
    created: "2025-03-28T21:45:11.56302001Z"
    dependencies:
    - condition: bitwarden-sdk-server.enabled
      name: bitwarden-sdk-server
      repository: oci://ghcr.io/external-secrets/charts
      version: v0.3.1
    description: External secret management for Kubernetes
    digest: 1504fceaaeb9ea440a54a3589280d42823758e8b984c9f6b15177d32ddf878c8
    home: https://github.com/external-secrets/external-secrets
    icon: https://raw.githubusercontent.com/external-secrets/external-secrets/main/assets/eso-logo-large.png
    keywords:
    - kubernetes-external-secrets
    - secrets
    kubeVersion: '>= 1.19.0-0'
    maintainers:
    - email: kellinmcavoy@gmail.com
      name: mcavoyk
    name: external-secrets
    type: application
    urls:
    - https://github.com/external-secrets/external-secrets/releases/download/helm-chart-0.15.1/external-secrets-0.15.1.tgz
    version: 0.15.1
```
